"""Initial PostgreSQL migration

Revision ID: 788e686934e1
Revises: fff8dc3751be
Create Date: 2026-01-18 00:39:38.402869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '788e686934e1'
down_revision = 'fff8dc3751be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('like_count')

    # ### end Alembic commands ###
