"""Add resubmission_count to Post

Revision ID: 90540b14a5d5
Revises: b7240cebee65
Create Date: 2026-01-15 14:35:21.975400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90540b14a5d5'
down_revision = 'b7240cebee65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resubmission_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('resubmission_count')

    # ### end Alembic commands ###
