"""Initial PostgreSQL migration

Revision ID: 9c70f1cccab1
Revises: 6a7543c0b276
Create Date: 2026-01-17 23:16:36.524192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c70f1cccab1'
down_revision = '6a7543c0b276'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('id_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('minipay_account', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('referral_link', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('referral_link')
        batch_op.drop_column('minipay_account')
        batch_op.drop_column('id_type')
        batch_op.drop_column('phone')
        batch_op.drop_column('category')
        batch_op.drop_column('description')
        batch_op.drop_column('location')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
