"""add published_at to post

Revision ID: b1453f02a1cb
Revises: 9d21eb4b9c99
Create Date: 2026-01-19 11:09:10.490992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1453f02a1cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_user')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('rejected_posts',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('rejected_posts',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('_alembic_tmp_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), nullable=True),
    sa.Column('trust_score', sa.INTEGER(), nullable=True),
    sa.Column('is_trusted', sa.BOOLEAN(), nullable=True),
    sa.Column('scheduled_at', sa.DATETIME(), nullable=True),
    sa.Column('approved_posts', sa.INTEGER(), nullable=True),
    sa.Column('rejected_posts', sa.INTEGER(), nullable=False),
    sa.Column('oauth_provider', sa.VARCHAR(length=50), nullable=True),
    sa.Column('oauth_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_premium', sa.BOOLEAN(), nullable=True),
    sa.Column('daily_limit', sa.INTEGER(), nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('location', sa.VARCHAR(length=50), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=80), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=30), nullable=True),
    sa.Column('id_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('referral_link', sa.VARCHAR(length=255), nullable=True),
    sa.Column('bank_account', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('oauth_id', name=op.f('uq_user_oauth_id')),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
