"""Initial schema with OAuth support

Revision ID: b7240cebee65
Revises: d9a515371b2b
Create Date: 2026-01-15 05:57:32.057346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7240cebee65'
down_revision = 'd9a515371b2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oauth_provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('oauth_id', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint('uq_user_oauth_id', ['oauth_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('oauth_id')
        batch_op.drop_column('oauth_provider')

    # ### end Alembic commands ###
