"""Initial PostgreSQL migration

Revision ID: bee6ab5564f6
Revises: 9c70f1cccab1
Create Date: 2026-01-17 23:51:12.825428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bee6ab5564f6'
down_revision = '9c70f1cccab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_account', sa.String(length=50), nullable=True))
        batch_op.drop_column('minipay_account')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('minipay_account', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('bank_account')

    # ### end Alembic commands ###
