"""Add is_premium column to User

Revision ID: d3a8169be43d
Revises: 5fe071d091b5
Create Date: 2026-01-16 14:27:48.848912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3a8169be43d'
down_revision = '5fe071d091b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('caption_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confidence', sa.Integer(), nullable=True))

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan', sa.String(length=20), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_premium', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_premium')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('plan')

    with op.batch_alter_table('caption_history', schema=None) as batch_op:
        batch_op.drop_column('confidence')

    op.drop_table('daily_usage')
    # ### end Alembic commands ###
