"""Add moderation fields to Post

Revision ID: d9a515371b2b
Revises: e2751b4997f3
Create Date: 2026-01-14 22:24:08.454592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9a515371b2b'
down_revision = 'e2751b4997f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('rejection_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('scheduled_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('trust_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_trusted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('scheduled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('approved_posts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rejected_posts', sa.Integer(), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.drop_column('rejected_posts')
        batch_op.drop_column('approved_posts')
        batch_op.drop_column('scheduled_at')
        batch_op.drop_column('is_trusted')
        batch_op.drop_column('trust_score')
        batch_op.drop_column('role')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('scheduled_at')
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('status')

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_column('role')
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
