"""Add user_id to posts

Revision ID: e2751b4997f3
Revises: 0135b54134df
Create Date: 2026-01-14 13:26:40.844588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2751b4997f3'
down_revision = '0135b54134df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(  "fk_post_user_id_user", 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(  "fk_post_user_id_user", type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
