"""Initial PostgreSQL migration

Revision ID: fff8dc3751be
Revises: bee6ab5564f6
Create Date: 2026-01-18 00:30:17.510469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fff8dc3751be'
down_revision = 'bee6ab5564f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read_time', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('read_time')

    # ### end Alembic commands ###
