"""Added tokens and limits to User model

Revision ID: 15b3548390f9
Revises: 1e8ec46981c7
Create Date: 2026-02-13 17:57:38.911124

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '15b3548390f9'
down_revision = '1e8ec46981c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('x_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('style', sa.String(length=20), nullable=True),
    sa.Column('text', sa.String(length=280), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('predicted_engagement', sa.JSON(), nullable=True),
    sa.Column('suggested_replies', sa.JSON(), nullable=True),
    sa.Column('best_post_time', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('x_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('thread', sa.JSON(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('predicted_engagement', sa.JSON(), nullable=True),
    sa.Column('suggested_replies', sa.JSON(), nullable=True),
    sa.Column('best_post_time', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('x_post_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('retweets', sa.Integer(), nullable=True),
    sa.Column('replies', sa.Integer(), nullable=True),
    sa.Column('engagement_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['x_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tokens', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_token_reset', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_token_reset')
        batch_op.drop_column('tokens')

    op.drop_table('x_post_metrics')
    op.drop_table('x_threads')
    op.drop_table('x_posts')
    # ### end Alembic commands ###
