"""Initial PostgreSQL migration

Revision ID: 011a5e118378
Revises: ddc12dcf06f2
Create Date: 2026-01-20 08:39:20.686278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '011a5e118378'
down_revision = 'ddc12dcf06f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_number', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('id_number')

    # ### end Alembic commands ###
