"""Add is_locked to Post

Revision ID: 088069ea6b8c
Revises: da706db36ed2
Create Date: 2026-01-30 00:25:53.714042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '088069ea6b8c'
down_revision = 'da706db36ed2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_locked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('is_locked')

    # ### end Alembic commands ###
