"""Initial PostgreSQL migration

Revision ID: 0c8b2ecac43e
Revises: 9a0b56ba1e90
Create Date: 2026-01-23 20:18:36.370449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c8b2ecac43e'
down_revision = '9a0b56ba1e90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caption_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caption', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caption_history', schema=None) as batch_op:
        batch_op.drop_column('caption')

    # ### end Alembic commands ###
