"""Add threads to XPost

Revision ID: 0d79ce552b75
Revises: 7fad1b1f383f
Create Date: 2026-03-03 22:57:41.944651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d79ce552b75'
down_revision = '7fad1b1f383f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('x_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('threads', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('x_posts', schema=None) as batch_op:
        batch_op.drop_column('threads')

    # ### end Alembic commands ###
