"""remove single label column

Revision ID: 1096d98385a4
Revises: a8989c39f92f
Create Date: 2026-01-01 21:28:30.739329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1096d98385a4'
down_revision = 'a8989c39f92f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('label')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
