"""caption and ads setup

Revision ID: 1e8ec46981c7
Revises: e20c2213aedc
Create Date: 2026-02-12 15:08:14.627953

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision = '1e8ec46981c7'
down_revision = 'e20c2213aedc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('target_url', sa.String(length=500), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_input', sa.Text(), nullable=False),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ad_click',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('x_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('style', sa.String(length=20), nullable=True),
    sa.Column('text', sa.String(length=280), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('predicted_engagement', sa.JSON(), nullable=True),
    sa.Column('suggested_replies', sa.JSON(), nullable=True),
    sa.Column('best_post_time', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('x_threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('thread', sa.JSON(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('predicted_engagement', sa.JSON(), nullable=True),
    sa.Column('suggested_replies', sa.JSON(), nullable=True),
    sa.Column('best_post_time', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('x_post_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('retweets', sa.Integer(), nullable=True),
    sa.Column('replies', sa.Integer(), nullable=True),
    sa.Column('engagement_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['x_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tokens', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_token_reset', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_token_reset')
        batch_op.drop_column('tokens')

    op.drop_table('x_post_metrics')
    op.drop_table('x_threads')
    op.drop_table('x_posts')
    op.drop_table('ad_click')
    op.drop_table('request')
    op.drop_table('ads')
    # ### end Alembic commands ###
