"""Add email logs table

Revision ID: 1fbb9e4214ad
Revises: 15b3548390f9
Create Date: 2026-02-14 12:29:43.958948

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column, select
from sqlalchemy import String, Integer, DateTime


# revision identifiers, used by Alembic.
revision = '1fbb9e4214ad'
down_revision = '1e8ec46981c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscriber_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.alter_column('subject',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.create_foreign_key('fk_emaillog_subscriber_id', 'subscriber', ['subscriber_id'], ['id'])
        batch_op.drop_column('recipient')

    from app.extensions import db
    from app.models import EmailLog

    session = db.session
    for row in session.query(EmailLog).filter(EmailLog.email.is_(None)):
    row.email = f'unknown+{row.id}@example.com'
    session.commit()

    with op.batch_alter_table('email_log', schema=None) as batch_op:
        batch_op.alter_column('email', existing_type=sa.String(length=255), nullable=False)

    op.create_index('ix_email_log_email', 'email_log', ['email'])
    op.create_index('ix_email_log_created_at', 'email_log', ['created_at'])

    with op.batch_alter_table('subscriber', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_email_sent', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_subscriber_user_id', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_email_log_email', table_name='email_log')
    op.drop_index('ix_email_log_created_at', table_name='email_log')
    with op.batch_alter_table('subscriber', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('last_email_sent')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('email_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('subject',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('email')
        batch_op.drop_column('subscriber_id')

    # ### end Alembic commands ###
