"""Add original text to XPost

Revision ID: 2057a53d50f5
Revises: 0d79ce552b75
Create Date: 2026-03-03 23:09:35.057773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2057a53d50f5'
down_revision = '0d79ce552b75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('x_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('x_posts', schema=None) as batch_op:
        batch_op.drop_column('original_text')

    # ### end Alembic commands ###
