"""add profile_visits to user

Revision ID: 2bd20ea6647c
Revises: 63494d5d3ddf
Create Date: 2026-01-21 23:54:18.550504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bd20ea6647c'
down_revision = '63494d5d3ddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shares', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('shares')

    # ### end Alembic commands ###
