"""Initial clean schema

Revision ID: 2c56a7a027c7
Revises: 
Create Date: 2025-12-28 22:40:03.356895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c56a7a027c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_breaking', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_editor_pick', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('is_editor_pick')
        batch_op.drop_column('is_breaking')

    # ### end Alembic commands ###
