"""Add image_url column to x_posts

Revision ID: 4e830a03e0c0
Revises: 053924c11a27
Create Date: 2026-02-25 13:19:43.879471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e830a03e0c0'
down_revision = '053924c11a27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('x_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('x_posts', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
