"""Initial PostgreSQL migration

Revision ID: 5353b56500e5
Revises: d645c8cf2090
Create Date: 2026-01-22 18:35:01.872499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5353b56500e5'
down_revision = 'd645c8cf2090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile_visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile_visits', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
