"""add profile_visits to user

Revision ID: 63494d5d3ddf
Revises: 90c8953132b0
Create Date: 2026-01-21 23:53:09.700352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63494d5d3ddf'
down_revision = '90c8953132b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_visits', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_visits')

    # ### end Alembic commands ###
