"""Add style column to CaptionHistory

Revision ID: 71534e4c567c
Revises: 15d60d7743c2
Create Date: 2026-01-27 00:49:47.767988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71534e4c567c'
down_revision = '15d60d7743c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caption_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('style', sa.String(length=20), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('input_text',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('tone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('length',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('platform',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caption_history', schema=None) as batch_op:
        batch_op.alter_column('platform',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('length',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('tone',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('input_text',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('style')

    # ### end Alembic commands ###
