"""Added name column to ads

Revision ID: 8dbc8cc5fbce
Revises: 4e830a03e0c0
Create Date: 2026-02-26 12:42:46.993940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dbc8cc5fbce'
down_revision = '4e830a03e0c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_clicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('clicked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ad_clicks', schema=None) as batch_op:
        batch_op.create_index('idx_click_ad_time', ['ad_id', 'clicked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_clicks_ad_id'), ['ad_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_clicks_clicked_at'), ['clicked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_clicks_user_id'), ['user_id'], unique=False)

    op.create_table('ad_impressions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ad_impressions', schema=None) as batch_op:
        batch_op.create_index('idx_impression_ad_time', ['ad_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_impressions_ad_id'), ['ad_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_impressions_created_at'), ['created_at'], unique=False)

    op.drop_table('ad_click')
    with op.batch_alter_table('ads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('type', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('html_code', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.DateTime(), nullable=True))
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index('idx_ad_active_location', ['active', 'location'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_ads_priority'), ['priority'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ads_priority'))
        batch_op.drop_index(batch_op.f('ix_ads_name'))
        batch_op.drop_index(batch_op.f('ix_ads_location'))
        batch_op.drop_index(batch_op.f('ix_ads_active'))
        batch_op.drop_index('idx_ad_active_location')
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('priority')
        batch_op.drop_column('html_code')
        batch_op.drop_column('type')
        batch_op.drop_column('name')

    op.create_table('ad_click',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ad_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('clicked_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ad_impressions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ad_impressions_created_at'))
        batch_op.drop_index(batch_op.f('ix_ad_impressions_ad_id'))
        batch_op.drop_index('idx_impression_ad_time')

    op.drop_table('ad_impressions')
    with op.batch_alter_table('ad_clicks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ad_clicks_user_id'))
        batch_op.drop_index(batch_op.f('ix_ad_clicks_clicked_at'))
        batch_op.drop_index(batch_op.f('ix_ad_clicks_ad_id'))
        batch_op.drop_index('idx_click_ad_time')

    op.drop_table('ad_clicks')
    # ### end Alembic commands ###
