"""Initial PostgreSQL migration

Revision ID: be0873f94c45
Revises: 5353b56500e5
Create Date: 2026-01-23 13:27:48.112239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be0873f94c45'
down_revision = '5353b56500e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_replied', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.drop_column('is_replied')
        batch_op.drop_column('is_read')
        batch_op.drop_column('type')
        batch_op.drop_column('subject')

    # ### end Alembic commands ###
