"""Add content_hash column to post

Revision ID: c03fc45019b8
Revises: 1fbb9e4214ad
Create Date: 2026-02-17 08:41:50.975072

"""
from alembic import op
import sqlalchemy as sa
from app.models import Post
import hashlib
from sqlalchemy.orm import Session
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'c03fc45019b8'
down_revision = '1fbb9e4214ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col['name'] for col in inspector.get_columns('post')]

    if 'content_hash' not in columns:
        op.add_column('post', sa.Column('content_hash', sa.String(length=64), nullable=True))

    # 2️⃣ Backfill existing post
    session = Session(bind=bind)
    posts = session.execute(sa.select(Post)).scalars().all()
    for post in posts:
        post.content_hash = hashlib.sha256(post.content.encode('utf-8')).hexdigest()
    session.commit()

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column(sa.Column('content_hash', nullable=False))
        batch_op.create_unique_constraint('uq_post_content_hash', ['content_hash'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('content_hash')

    # ### end Alembic commands ###
