"""Add Tribe conversation fields

Revision ID: c2788c3123ec
Revises: ea796b86515f
Create Date: 2026-09-05 15:26:28.417996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2788c3123ec'
down_revision = 'ea796b86515f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tribe_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('tribe_title', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('tribe_description', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('tribe_button_text', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('tribe_button_text')
        batch_op.drop_column('tribe_description')
        batch_op.drop_column('tribe_title')
        batch_op.drop_column('tribe_url')

    # ### end Alembic commands ###
