"""Add email completion

Revision ID: c56a5b085341
Revises: 93727053016d
Create Date: 2026-08-03 20:20:25.110679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c56a5b085341'
down_revision = '93727053016d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_recipient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sending_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_attempt_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_campaign_recipient_batch_number'), ['batch_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_recipient_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_recipient_status'), ['status'], unique=False)

    with op.batch_alter_table('email_campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('paused_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('completed_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('current_batch')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_batch', sa.INTEGER(), nullable=True))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('completed_count')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('paused_at')
        batch_op.drop_column('started_at')

    with op.batch_alter_table('campaign_recipient', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_recipient_status'))
        batch_op.drop_index(batch_op.f('ix_campaign_recipient_campaign_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_recipient_batch_number'))
        batch_op.drop_column('last_attempt_at')
        batch_op.drop_column('sending_started_at')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
