"""Initial PostgreSQL migration

Revision ID: d645c8cf2090
Revises: 48a2ceb869dc
Create Date: 2026-01-22 18:30:43.233314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd645c8cf2090'
down_revision = '48a2ceb869dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visited_user_id', sa.Integer(), nullable=False),
    sa.Column('visitor_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['visited_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['visitor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_visits')
    # ### end Alembic commands ###
