"""add column to XPost model

Revision ID: d729a63b085e
Revises: 2057a53d50f5
Create Date: 2026-03-05 21:35:29.513035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd729a63b085e'
down_revision = '2057a53d50f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('x_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('captions', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('x_posts', schema=None) as batch_op:
        batch_op.drop_column('captions')

    # ### end Alembic commands ###
