"""Initial clean migration

Revision ID: da706db36ed2
Revises: 71534e4c567c
Create Date: 2026-01-29 22:18:33.883234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da706db36ed2'
down_revision = '71534e4c567c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reaction', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_id', 'user_id', name='unique_comment_reaction')
    )
    with op.batch_alter_table('comment_reactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_reactions_comment_id'), ['comment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_reactions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment_reactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_reactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_comment_reactions_comment_id'))

    op.drop_table('comment_reactions')
    # ### end Alembic commands ###
