"""Initial PostgreSQL migration

Revision ID: ddc12dcf06f2
Revises: 8eccb5dc8e17
Create Date: 2026-01-19 22:53:53.616614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddc12dcf06f2'
down_revision = '8eccb5dc8e17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_completed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_completed')

    # ### end Alembic commands ###
