"""Analysis cleaning

Revision ID: e20c2213aedc
Revises: 0f1f2161f5a7
Create Date: 2026-02-11 12:25:17.596522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e20c2213aedc'
down_revision = '0f1f2161f5a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page_view', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read_time', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page_view', schema=None) as batch_op:
        batch_op.drop_column('read_time')

    # ### end Alembic commands ###
