"""Add draft audience

Revision ID: ea796b86515f
Revises: c56a5b085341
Create Date: 2026-08-03 23:14:51.830631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea796b86515f'
down_revision = 'c56a5b085341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('digest_draft', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audience', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('subscriber_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_digest_draft_subscriber", 'subscriber', ['subscriber_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('digest_draft', schema=None) as batch_op:
        batch_op.drop_constraint("fk_digest_draft_subscriber", type_='foreignkey')
        batch_op.drop_column('subscriber_id')
        batch_op.drop_column('audience')

    # ### end Alembic commands ###
